export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const LOAD_TODOS_REQUEST = 'LOAD_TODOS_REQUEST';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const CLEAR_TODOS_REQUEST = 'CLEAR_TODOS_REQUEST';
export const CLEAR_TODOS_SUCCESS = 'CLEAR_TODOS_SUCCESS';
export const addTodoRequest = (text) => ({ type: ADD_TODO_REQUEST, payload: text });
export const loadTodosRequest = () => ({ type: LOAD_TODOS_REQUEST });
export const deleteTodoRequest = (id) => ({ type: DELETE_TODO_REQUEST, payload: id });
export const toggleTodoRequest = (id) => ({ type: TOGGLE_TODO_REQUEST, payload: id });
export const editTodoRequest = (id, newText) => ({ type: EDIT_TODO_REQUEST, payload: { id, newText } });
export const clearTodosRequest = () => ({ type: CLEAR_TODOS_REQUEST });
